name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        if [[ ${{ matrix.python-version }} == '3.7' ]]; then
          echo "asgiref==3.7.2" > requirements.txt
        else
          echo "asgiref==3.8.1" > requirements.txt
        fi
        echo "Django==4.2.13" >> requirements.txt
        echo "pytest==8.2.2" >> requirements.txt
        echo "pytest-django==4.8.0" >> requirements.txt
        echo "sqlparse==0.5.0" >> requirements.txt
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test base.tests
